plugins {
    id 'com.android.application'
}

android {
    namespace 'com.interfaz.teyesdeveloperoptions'
    compileSdk 34
    compileSdkExtension 12
    buildToolsVersion '34.0.0'

    defaultConfig {
        applicationId 'com.interfaz.teyesdeveloperoptions'
        minSdk 23
        targetSdk 33
        versionCode 602
        versionName '0.6.2'
    }
}
